name: FlashWhite
version: '1.1.1'
main: ctx.mr_hares.flashWhite.FlashWhite
api-version: '1.21'
authors: [ mr_hares ]

commands:
  flashwhite:
    permissions: flashwhite.use
    aliases: [fw]

permissions:
  flashwhite.use:
    description: The ability to use the plugin's basic commands.
  flashwhite.reload:
    description: The ability to reload the configuration.